version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: interview_bot
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Initialize database with our schema and sample data
      - ./database/migrations:/docker-entrypoint-initdb.d/migrations
      - ./database/seed:/docker-entrypoint-initdb.d/seed
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  interview-bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.docker
    restart: unless-stopped

volumes:
  postgres_data: